<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.tds</groupId>
        <artifactId>dos-parent</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>dos-dal</artifactId>
    <packaging>jar</packaging>
    <name>DOS-dal</name>
    <description>交付平台数据访问层</description>

    <dependencies>
        <dependency>
            <groupId>com.tds</groupId>
            <artifactId>dos-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>